export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR';

export const BUS_DETAILS_REQUEST = 'BUS_DETAILS_REQUEST';
export const BUS_DETAILS_SUCCESS = 'BUS_DETAILS_SUCCESS';
export const BUS_DETAILS_ERROR = 'BUS_DETAILS_ERROR';
